### ISSUE TITLE
Feat: Make weekday name length configurable

### ISSUE THREAD

**Issue by raphaelokon** [WickyNilliams/cally#66] opened 2024-09-23 14:29 UTC
I think it would be feasible to let the `shortDayName` be configurable between 'narrow' | 'short'? → https://github.com/WickyNilliams/cally/blob/main/src/calendar-month/useCalendarMonth.ts#L21

**Comment by WickyNilliams** [comment] 2024-11-01 22:42
Just realised this is a duplicate of #24. Closing in favour of that

**Closed by WickyNilliams** 2024-11-01 22:42 UTC

**Comment by WickyNilliams** [comment] 2025-02-08 17:15
Hey @raphaelokon this has now been published as part of `v0.8.0`. Sorry about the delay!
