### ISSUE TITLE
Calendar representation for value in `CalendarDate` appears very wrong

### ISSUE THREAD

**Issue by atmgrifter00** [WickyNilliams/cally#12] opened 2024-04-03 21:46 UTC
On your [example page](https://wicky.nillia.ms/cally/components/calendar-date/) (and even in my local exploration) the `CalendarMonth` widget is not being correctly represented in a couple of ways:
1) The highlighted day specified by the `value` property is a month behind. In you example, value is specified as "2024-01-10" (January 10th 2024), but the highlighted day is December 10th, 2023. I see the same inconsistency locally.
2) Perhaps worse, is that the days do not begin on the proper day for the displayed month and year. On your example page, the month of December in 2023 is starting on Sunday, when it should be Friday. I'll note that the month of 12/24 _does_ start on a Sunday.

**Comment by WickyNilliams** [comment] 2024-04-04 10:02
Thanks. Can you give some further information to help me out? What browser, version, and OS? What is your system locale?

Seems like there's an off by one error from your description, which is a classic error for JS Dates since months are zero based.

However, everything looks fine to me. I've tested on Firefox and chrome on my phone. 

![Screenshot_20240404-105523](https://github.com/WickyNilliams/cally/assets/1091390/0b929f8b-1afe-436e-9340-c970370f210a)

Perhaps I've misunderstood.

**Comment by atmgrifter00** [comment] 2024-04-04 12:35
I see this in both Firefox and Chrome:
![image](https://github.com/WickyNilliams/cally/assets/26874831/bac48c1d-df96-4897-97ca-91281277d6b9)

**Comment by atmgrifter00** [comment] 2024-04-04 13:25
I'll check with others on my team to see if they see the same issue.

**Comment by kswedberg** [comment] 2024-04-04 15:50
fwiw, I'm seeing this issue, as well, on your demo page at https://wicky.nillia.ms/cally/guides/theming/ (using a Chromium-flavored browser on MacOS). Here is a screenshot
<img width="891" alt="image" src="https://github.com/WickyNilliams/cally/assets/3485/d03871c5-b46f-4d50-bf5d-5041aa766070">

**Comment by WickyNilliams** [comment] 2024-04-04 16:01
Thanks, good to have a second confirmation. I'm not able to reproduce in either case. It looks like the issue is the headings are incorrect rather than the month itself.

What do you get if you log in the console:

```js
console.log(navigator.languages[0])
```

**Comment by WickyNilliams** [comment] 2024-04-04 16:01
But hmm it explicitly sets the the locale there, so that shouldn't matter. Interested to hear anyway

**Comment by kswedberg** [comment] 2024-04-04 16:19
I get `en-US`. Not sure where you're located geographically, but it could have something to do with timezone offsets. For example, if I log the result of `const date = new Date(Date.UTC(2024, 1 - 1, 1))` (from https://github.com/WickyNilliams/cally/blob/main/src/utils/temporal.ts#L21), I get "Sun Dec 31 2023 19:00:00 GMT-0500 (Eastern Standard Time)".

If I then log `new Intl.DateTimeFormat('en-GB').format(date)`, I get "31/12/2023"

**Comment by WickyNilliams** [comment] 2024-04-04 16:41
That's got to be it! Thanks for digging in. I wonder if I explicitly set the timeZone option of the DateTimeFormat to `UTC` it'll fix it.

**Comment by kswedberg** [comment] 2024-04-04 16:52
Yes, that should do it: `new Intl.DateTimeFormat('en-GB', {timeZone: 'UTC'}).format(date) === '01/01/2024'`

**Comment by WickyNilliams** [comment] 2024-04-04 17:31
OK, i just merged a PR which uses UTC `timeZone` across the board. The docs actually use a local build of the lib (not the npm version). So before I publish to npm, can you confirm whether this has fixed the issue? https://wicky.nillia.ms/cally/components/calendar-date/

**Comment by kswedberg** [comment] 2024-04-04 17:50
Yes, LGTM!

**Comment by WickyNilliams** [comment] 2024-04-04 17:54
Released as `0.4.2`. Thanks so much for your help

**Comment by atmgrifter00** [comment] 2024-04-04 18:01
So, not to rain on the parade, but when I go to [https://wicky.nillia.ms/cally/components/calendar-date/](https://wicky.nillia.ms/cally/components/calendar-date/), I see:
![image](https://github.com/WickyNilliams/cally/assets/26874831/644aff84-23c2-4d20-b12c-58c4a2626bc3)

and while it's now correctly selecting the expected day of the displayed year, the days do not begin on the proper day of the week. January 1st 2024 is on a Monday.

**Comment by WickyNilliams** [comment] 2024-04-04 18:05
😂 Damn it

I think I know the cause. I'll fix tomorrow and reopen in the meanwhile

**Comment by WickyNilliams** [comment] 2024-04-05 11:44
OK, i have merged another PR. Now all instances of `Intl.DateTimeFormat` use the `"UTC"` timezone. Can you let me know if this has resolved the issue?

**Comment by WickyNilliams** [comment] 2024-04-05 13:26
It was the same bug as before, just a different manifestation. 

I use DateTimeFormat to get day names based on locale. But the user's timezone could introduce drift in the output. For the same reason it output `new Date(2024, 0, 1)` as December due to timezone differences, it treated a Monday as a Sunday and so on.

**Comment by WickyNilliams** [comment] 2024-04-05 14:11
Published as `0.4.3`. Will close this now. Hoping that's the last of the issues here :)

**Closed by WickyNilliams** 2024-04-05 14:11 UTC
Labels: bug
