### ISSUE TITLE
Fix onRangestart and onRangeend Events in Cally Library

### ISSUE THREAD

**Issue by Cata1989** [WickyNilliams/cally#47] opened 2024-05-29 10:08 UTC
The onRangestart and onRangeend events in the Cally library do not always function correctly. To avoid ESLint complaints in StencilJS, the following rules need to be added:

`// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-expect-error
onRangestart={this.handleCalendarRangestart}
onRangeend={this.handleCalendarRangeend}`

Please fix these event issues or consider changing the event handling mechanism to improve reliability and performance.

**Comment by WickyNilliams** [comment] 2024-05-29 10:15
> do not always function correctly

in what way?

> avoid ESLint complaints

what is it complaining about?

> consider changing the event handling mechanism 

it uses standard events, there's nothing that can be changed

**Comment by endv-bogdanb** [comment] 2024-05-29 11:59
Hi, the issue is the name of the events `onRangeStart` / `onRangeEnd` are not recognised if attached to `<calendar-range>`. Can you rename them in the types to `onRangestart` / `onRangeend`. 

Currently we are using [exported interfaces to enhance our jsx](https://github.com/Endava/BEEQ/blob/main/packages/beeq/src/global/scripts/global.ts#L7)

<img width="458" alt="image" src="https://github.com/WickyNilliams/cally/assets/109202804/03d0c6ee-26c5-4879-9704-7ed0df5aa1fa">

**Comment by WickyNilliams** [comment] 2024-05-29 12:35
Oh it's a typescript issue? You can probably get away with mapping the types yourself:

```ts
type MapEventName<T> = T extends `on${infer Rest}`
  ? `on${Capitalize<Lowercase<Rest>>}`
  : T;

type MapEvents<T> = {
  [K in keyof T as MapEventName<K>]: T[K];
};

type MappedRangeProps = MapEvents<CalendarRangeProps>
```

**Comment by WickyNilliams** [comment] 2024-05-29 15:54
Closing for now, as I think the above will solve your issues

**Closed by WickyNilliams** 2024-05-29 15:54 UTC
